### PR TITLE
package launch renamed to only build on darwin

### PR DESCRIPTION
**Pull request by pda**
Rename `dev/launch/launch.go` → `dev/launch/launch_darwin.go` so that it only attempts to builds on macOS. It breaks on other OS e.g. Linux:

```
?   	github.com/puma/puma-dev/cmd/puma-dev	[no test files]
?   	github.com/puma/puma-dev/dev	[no test files]
# github.com/puma/puma-dev/dev/launch
/usr/bin/ld: $WORK/b127/_x002.o: in function `_cgo_a57b4e3f8339_Cfunc_launch_activate_socket':
/tmp/go-build/cgo-gcc-prolog:67: undefined reference to `launch_activate_socket'
collect2: error: ld returned 1 exit status
ok  	github.com/puma/puma-dev/httpu/internal	(cached)
ok  	github.com/puma/puma-dev/httputil	(cached)
ok  	github.com/puma/puma-dev/linebuffer	(cached)
```

`launch.go` in `package launch` contains macOS-specific C function prototype `launch_active_socket`. The package is only referenced in `dev/http_darwin.go` which is also darwin-only.

This change gets `go test ./...` working on Linux:

```
?   	github.com/puma/puma-dev/cmd/puma-dev	[no test files]
?   	github.com/puma/puma-dev/dev	[no test files]
?   	github.com/puma/puma-dev/homedir	[no test files]
?   	github.com/puma/puma-dev/httpu	[no test files]
ok  	github.com/puma/puma-dev/httpu/internal	(cached)
ok  	github.com/puma/puma-dev/httputil	(cached)
ok  	github.com/puma/puma-dev/linebuffer	(cached)
?   	github.com/puma/puma-dev/watch	[no test files]
```

### CODE REVIEW

**Comment by nonrational** [comment]
Once this merges, I'll back out https://github.com/puma/puma-dev/pull/221/commits/b69a977e4e33c9efb7f80e4e15a078d319b62e02 from my PR(s).

**Comment by nateberkopec** [comment]
Resolve conflicts and I'll hit the big green button

**Comment by nonrational** [comment]
Well, my commit merge first. Still, the `_darwin.go` suffix approach seems preferable to the build header; much less cryptic. 

I'd advocate for reverting https://github.com/puma/puma-dev/commit/b69a977e4e33c9efb7f80e4e15a078d319b62e02 and keeping the file rename. 🙌

**Comment by pda** [comment]
This PR is now a revert of b69a977 (👋 thanks @nonrational, I didn't realise you already had this) and a rename of the source file to use implicit `..._darwin.go` build constraint. For reference, Go's build constraints are documented at https://golang.org/pkg/go/build/ 

I agree we should go with this filename-based constraints (where possible) for consistency with the rest of the codebase:

```
$ git switch master
Switched to branch 'master'
Your branch is up to date with 'origin/master'.

$ rg --glob '!vendor' -- '\+build'
dev/launch/launch.go
1:// +build darwin

$ find . -path ./vendor -prune -o -print | rg '_(linux|darwin).go'
./cmd/puma-dev/main_darwin.go
./cmd/puma-dev/main_linux.go
./dev/http_darwin.go
./dev/ssl_darwin.go
./dev/ssl_linux.go
./dev/http_linux.go
./watch/watch_darwin.go
./watch/watch_linux.go
```

**Pull request merged**
