### PR TITLE
Update vendored github.com/fsnotify/fsevents

### PR DESCRIPTION
**Pull request by lmars**
To pull in the following fix:

https://github.com/fsnotify/fsevents/pull/41

### CODE REVIEW

**Comment by nateberkopec** [comment]
I may be missing something here, but this does not fix the issue for me.

On a freshly cloned puma-dev, with this branch checkout out:

```
 speedshop $ go build ./cmd/puma-dev
# github.com/puma/puma-dev/vendor/github.com/fsnotify/fsevents
../../../../go/src/github.com/puma/puma-dev/vendor/github.com/fsnotify/fsevents/wrap.go:115:59: cannot use nil as type _Ctype_CFAllocatorRef in assignment
../../../../go/src/github.com/puma/puma-dev/vendor/github.com/fsnotify/fsevents/wrap.go:122:42: cannot use nil as type _Ctype_CFAllocatorRef in assignment
../../../../go/src/github.com/puma/puma-dev/vendor/github.com/fsnotify/fsevents/wrap.go:175:37: cannot use nil as type _Ctype_CFAllocatorRef in argument to _Cfunc_CFStringCreateWithCString
```

...which is the same error I get on master.

**Comment by lmars** [comment]
It works for me:

```
$ git reflog show HEAD
f366088 (HEAD -> update-fsevents, lmars/update-fsevents) HEAD@{0}: commit: Update vendored github.com/fsnotify/fsevents

$ go build ./cmd/puma-dev

$ echo $?
0
```

**Comment by nateberkopec** [comment]
Newbie GOPATH issues, sorry. Confirmed fixed.

**Comment by lmars** [comment]
Good ol' GOPATH 😉 

Thanks for the merge!

**Pull request merged**
