### PR TITLE
remove gb

### PR DESCRIPTION
**Pull request by catatsuy**
Reason for suggestion:

* the vendor behavior is default on later Go1.6
* We do not need gb

Problem:

* I did not edit `Makefile` because I cannot be designated for each OS the `main_darwin.go` and the `main_linux.go`. I want to discuss the way.
* Go cannot import `internal` package. In my opinion, it would be implemented leakage of `gb`.

### CODE REVIEW

**Comment by evanphx** [comment]
If I'm going to do this, I'm not going to leave the `src/` directory at all.

One reason I like gb is that it gives you unique namespaces that can be imported directly, such as `import "puma/watch"`.

@davecheney: thoughts?

**Comment by davecheney** [comment]
I'm sorry I don't know the backstory of this ticket, but sadly gb has little to offer a library author at this point. It's really only a tool for products at this stage.

**Comment by evanphx** [comment]
@davecheney puma-dev is a product, not a library, and that's why I opted to use it.

**Comment by davecheney** [comment]
Cool. This rewrite looks good gb or no gb. I think it's a good idea to keep your source in 

`$PROJECT/src/github.com/puma/puma-dev`

**Comment by catatsuy** [comment]
@evanphx 
I thought that I removed the `src/` directory. But, if I did so, the difference is very large.
If you do not mind it, it is possible that I will do it.

I think you should write the full path for import in Go. Because it is the rule in Go.

**Comment by evanphx** [comment]
Since it will always conflict, I should probably do the change.

**Comment by catatsuy** [comment]
I hope that the puma-dev will be able to build without gb. If this pull request is merged, it is possible.

What I should be doing in order to merge this pull request? I will do as much as I can.

**Comment by evanphx** [comment]
@catatsuy I went ahead and did the change since I needed to resolve a few things that would have been difficult to explain. You should be able to build by running `go build ./cmd/puma-dev` now!

**Comment by catatsuy** [comment]
thank you!

**Pull request closed without merging**
