### PR TITLE
Allow opt-out of dotfile sourcing

### PR DESCRIPTION
**Pull request by drinks**
As an alternative approach to #268 than #271, I wanted to explore allowing the execution shell to leverage its environment to individually toggle each dotfile on or off.

I'm pretty flexible on var names here and would be happy to add tests if needed, I just didn't see any for the file or behaviors in question.

Let me know what else you'd need to give this a try!

### CODE REVIEW

**Comment by nonrational** [comment]
Interesting! Given this behavior is entirely opt-in, I think it's a fine solution. 👍

**Comment by chmurph2** [comment]
Thanks @nonrational. What's the schedule like for new Puma-dev releases?

**Comment by nonrational** [comment]
Mostly ad-hoc. Probably within the next 48hrs.

**Comment by nonrational** [comment]
v0.16.0 is now available via `brew`.

**Pull request merged**
